<?php

namespace App\Models;

use App\Observers\TokenForUserRegistrationObserver;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class TokenForUserRegistration extends Model
{
    use HasFactory;

    public static $tokenAliveMinutes = 40;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::observe(TokenForUserRegistrationObserver::class);
    }
}
